build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: apcupsd"
  org.opencontainers.image.description: "Home Assistant Add-on serving the Power Management daemon for Ethernet-connected APC UPS."
  org.opencontainers.image.source: "https://github.com/twasilczyk/apcupsd-ha"
  org.opencontainers.image.licenses: "MIT"
codenotary:
  base_image: notary@home-assistant.io
  signer: codenotary@wasilczyk.pl
