name: "apcupsd"
description: "Power Management daemon for NMC-equipped APC UPS"
url: "https://github.com/twasilczyk/apcupsd-ha"
version: "0.0.167"
slug: "apcupsd"
ports:
  3551/tcp: 3551
ports_description:
  3551/tcp: Network Information Server (NIS) port
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  deviceaddr: ''
  deviceport: 161
  snmpcommunity: 'public'
  polltime: 60
schema:
  deviceaddr: str
  deviceport: port
  snmpcommunity: str
  polltime: int(1,3600)
